SignUp screen
wolox-training/jh-react pull request #1
Opened 2021-12-29 01:04 UTC by miguelhenaoa

## Summary

- Screen and sign up form
- Update React Hook Form library

## Screenshots

![image](https://user-images.githubusercontent.com/84401563/147594598-3ad8cb79-531b-4981-8cea-1a52681a87b8.png)

## Trello Card

https://trello.com/c/OYU7tQFY

2022-01-03 16:36 UTC, TaloMontes commented on src/screens/SignUp/index.tsx
> +                value: /\S+@\S+\.\S+/,
Add const with this regex

2022-01-03 16:36 UTC, TaloMontes commented on src/screens/SignUp/index.tsx
> +                value: /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/,
same

2022-01-03 16:36 UTC, TaloMontes commented on src/scss/buttons.scss
> +  border-radius: 5px;
sort alphabetically

2022-01-03 17:09 UTC, miguelhenaoa commented on src/screens/SignUp/index.tsx
> +                value: /\S+@\S+\.\S+/,
Done!

2022-01-03 17:09 UTC, miguelhenaoa commented on src/scss/buttons.scss
> +  border-radius: 5px;
Done!

2022-01-04 13:14 UTC, TaloMontes submitted a review, later dismissed

2022-01-07 20:22 UTC, alejobh requested changes
Nice work! just a few comments

2022-01-07 20:22 UTC, alejobh commented on src/components/Input/styles.module.scss
> +}
add EOF

2022-01-07 20:22 UTC, alejobh commented on src/constants/regex.ts
> +export const regexEmail = /\S+@\S+\.\S+/;
you can name this file forms.ts

2022-01-07 20:22 UTC, alejobh commented on src/scss/variables/_colors.scss
> +$silver-chalice: #A8A8A8;
Add EOF

2022-01-07 20:22 UTC, alejobh commented on src/scss/forms.scss
> +}
this is not used

2022-01-07 20:22 UTC, alejobh commented on src/scss/forms.scss
> +}
this is not used

2022-01-07 20:22 UTC, alejobh commented on src/scss/forms.scss
> +@import "./variables/colors";
i think all of this file does not need to be a global style

2022-01-07 20:22 UTC, alejobh commented on src/scss/forms.scss
> +}
this is the only class used, and i think login and register screens looks the same.
What you can do is a presentational Wrapper component that receives a children. Then create a SignupForm and LoginForm components to be the children of this wrapper component.
For now and this PR this is ok. But refactor when facing login screen

2022-01-11 14:40 UTC, miguelhenaoa commented on src/scss/forms.scss
> +}
Removed!

2022-01-11 14:40 UTC, miguelhenaoa commented on src/scss/forms.scss
> +}
Removed!

2022-01-11 14:40 UTC, miguelhenaoa commented on src/scss/forms.scss
> +}
I will keep this in mind for when I make that screen

2022-01-11 19:58 UTC, alejobh approved these changes
Nice work!

2022-01-11 19:58 UTC, alejobh commented on src/components/FormCard/index.tsx
> +function FormCard({ children }: FormCardProps) {
we usually name component's interface `Props`, Fix in the next PR

2022-01-12 15:07 UTC, miguelhenaoa commented on src/components/FormCard/index.tsx
> +function FormCard({ children }: FormCardProps) {
Ok, I will keep in mind for the next cards.

2022-01-12 15:07 UTC, merged