Internationalization
wolox-training/jh-react pull request #2
Opened 2022-01-05 20:57 UTC by miguelhenaoa

## Summary

- Update i18n config
- Add files of translation
- Change of texts to `t` function
## Screenshots

![image](https://user-images.githubusercontent.com/84401563/148287680-c9a69d95-375b-4ddb-b09f-dac0ef353f73.png)

![image](https://user-images.githubusercontent.com/84401563/148287717-8a3256cc-a748-4330-9132-9ffa17f7c324.png)

## Trello Card

https://trello.com/c/VIs9wVYN

2022-01-07 20:47 UTC, alejobh requested changes
Great work!

2022-01-07 20:47 UTC, alejobh commented on .eslintcache
> +[{"/Users/juan.m.henao.arias/Documents/GitHub/jh-react/src/screens/SignUp/index.tsx":"1","/Users/juan.m.henao.arias/Documents/GitHub/jh-react/src/components/Input/index.tsx":"2","/Users/juan.m.henao.
this file should be on gitignore

2022-01-07 20:47 UTC, alejobh commented on package.json
> +    "i18next-http-backend": "^1.3.1",
this package is not necessary, you dont have a backend for translations

2022-01-07 20:47 UTC, alejobh commented on public/locales/en/translation.json
> +{
currently on react's department, we dont use json for translations approach.
We use a i18n.ts file to add translation for just the portion of the translations given by a key in the component level:.
example:

```
import i18next from 'i18next';

i18next.addResources('es', 'SignUp', {
  "firstName": "Nombre",
  "lastName": "Apellido",
  "email": "Correo",
  "password": "Contraseña",
  "passwordConfirmation": "Confirmación de contraseña"
});

i18next.addResources('en', 'SignUp', {
 "firstName": "First Name",
  "lastName": "Last Name",
  "email": "Email",
  "password": "Password",    
  "passwordConfirmation": "Password Confirmation"
});
```

2022-01-07 20:47 UTC, alejobh commented on public/locales/en/translation.json
> +{
When you have general translations. They are put on a file i18n.ts at constants global folder

2022-01-07 20:47 UTC, alejobh commented on src/components/Navbar/styles.module.scss
> +}
add EOF

2022-01-07 20:47 UTC, alejobh commented on src/config/i18n.js
this lines are missing in order to add all translations

```
function requireAll(requireContext) {
  return requireContext.keys().map(requireContext);
}

requireAll(require.context('..', true, /i18n\.(js|ts)$/));
```
What this does is require at src level all down levels searching files that are named like i18n.{ts|js} and add them to the translations scope

2022-01-07 20:47 UTC, alejobh commented on src/screens/SignUp/i18n.ts
> +import i18next from 'i18next';
??

2022-01-07 20:47 UTC, alejobh commented on src/screens/SignUp/index.tsx
> +            label={t('signUp.lastName')}
when using i18n.ts files to add translations this should be like `t('SignUp:lastName')` as example

2022-01-07 20:47 UTC, alejobh commented on src/screens/SignUp/index.tsx
> +            {...register('firstName', { required: t('validations.required') as string })}
`{...register('firstName', { required: t<string>('validations.required') })}` does this change satisfy ts constraint?
Because `as string` is a type assertion that is not very good

2022-01-07 20:47 UTC, alejobh commented on src/scss/buttons.scss
> +.btn-lng-es {
i think this could be a `&--es{` prefix inside the upper class? the only thin that changes is the color and background color

2022-01-07 20:47 UTC, alejobh commented on src/scss/buttons.scss
> +.btn-lng {
use lang please. lng could be confusing

2022-01-11 16:43 UTC, miguelhenaoa commented on src/scss/buttons.scss
> +.btn-lng-es {
When I make the change, the following happens: with this code 

```SCSS
.btn-lang {
  border: 2px solid $earls-green;
  padding: 5px 3px;

  &--es{ 
    background-color: $earls-green;
    color: $white;
  }
}
```
I get the following:
<img width="63" alt="Captura de Pantalla 2022-01-11 a la(s) 11 22 11 a  m" src="https://user-images.githubusercontent.com/84401563/148982992-66fe9c89-bad3-4b77-947d-6cc65b8bbcd6.png">

2022-01-11 16:49 UTC, miguelhenaoa commented on src/scss/buttons.scss
> +.btn-lng {
I have already changed it

2022-01-11 16:52 UTC, miguelhenaoa commented on src/components/Navbar/styles.module.scss
> +}
Done!

2022-01-11 16:54 UTC, miguelhenaoa commented on src/screens/SignUp/index.tsx
> +            label={t('signUp.lastName')}
Done!

2022-01-11 20:11 UTC, alejobh requested changes
A bit more things here

2022-01-11 20:11 UTC, alejobh commented on .eslintcache
> +[{"/Users/juan.m.henao.arias/Documents/GitHub/jh-react/src/screens/SignUp/index.tsx":"1","/Users/juan.m.henao.arias/Documents/GitHub/jh-react/src/components/Input/index.tsx":"2","/Users/juan.m.henao.
and removed from the repository

2022-01-11 20:11 UTC, alejobh commented on src/screens/SignUp/i18n.ts
> +});
This gonna be a problem, because `Validations` will become as global key, if anything only has to do with the component itself, should be inside `SignUp`. Same for the others...
The idea of a i18n.ts file at component level is to have preferably  one key with the name of the component

2022-01-11 20:11 UTC, alejobh commented on src/screens/SignUp/i18n.ts
> +});
same

2022-01-11 20:11 UTC, alejobh commented on src/components/Navbar/index.tsx
> +      <button type="button" className="btn-lang-es" onClick={() => handleClick('es')}>
this should be `btn-lang btn-lang-es`, and i think that toggling button should change the UI to the active one.

2022-01-12 17:46 UTC, miguelhenaoa commented on src/screens/SignUp/i18n.ts
> +});
Ok, I understand. I have made the change

2022-01-12 17:46 UTC, miguelhenaoa commented on src/screens/SignUp/i18n.ts
> +});
Done!

2022-01-12 17:47 UTC, miguelhenaoa commented on src/components/Navbar/index.tsx
> +      <button type="button" className="btn-lang-es" onClick={() => handleClick('es')}>
Done!

2022-01-24 15:23 UTC, TaloMontes submitted a review, later dismissed

2022-02-07 19:42 UTC, alejobh commented on src/components/Navbar/index.tsx
> +  const [isActiveEn, setActiveEn] = useState(false);
use only one state for this `isSpanish`

2022-02-07 20:29 UTC, alejobh approved these changes

2022-02-07 20:30 UTC, merged