Sign up service
wolox-training/jh-react pull request #3
Opened 2022-01-12 18:22 UTC by miguelhenaoa

## Summary

- Add API configuration
- Create UsersServive
- Call API from view
## Screenshots

[Change!] Show the screenshots of the views you modified.
![image](https://user-images.githubusercontent.com/84401563/149199047-6e75059e-9e08-4a95-8d74-f19486c58963.png)

## Trello Card

https://trello.com/c/OEPmfU90

2022-01-28 20:54 UTC, TaloMontes commented on src/config/api.js
> +const baseURL = 'https://books-training-rails.herokuapp.com/api/v1' || 'http://wolox.com';
delete wolox url

2022-02-01 13:48 UTC, TaloMontes submitted a review, later dismissed

2022-02-07 19:56 UTC, alejobh requested changes
nice work!

2022-02-07 19:56 UTC, alejobh commented on src/components/App/index.tsx
>  import Home from 'screens/Home/index';
remove index

2022-02-07 19:56 UTC, alejobh commented on src/config/api.js
> +const baseURL = 'https://books-training-rails.herokuapp.com/api/v1';
this should be placed on a .env variable normally called `REACT_APP_API_BASE_URL`

2022-02-07 19:56 UTC, alejobh commented on src/screens/SignUp/index.tsx
> +import Loading from '../../components/Spinner/components/loading';
use absolute routes

2022-02-07 19:56 UTC, alejobh commented on src/screens/SignUp/index.tsx
> +    }
this could be different, use problem or code from the request error

2022-02-07 19:56 UTC, alejobh commented on src/screens/SignUp/index.tsx
> +  const onSubmit = () => {
onSubmit gives you the values as function param

2022-02-07 19:56 UTC, alejobh commented on src/screens/SignUp/index.tsx
> +  const { isLoading, isError, mutate } = useMutation((data: User) => signUp(data), {
`const { isLoading, isError, mutate } = useMutation(signUp, {`

2022-02-07 19:56 UTC, alejobh commented on src/screens/SignUp/index.tsx
> +  const onSubmit = () => {
`const onSubmit = (values: User) => {`

2022-02-07 19:56 UTC, alejobh commented on src/screens/SignUp/index.tsx
> +
avoid blank lines on the jsx

2022-02-07 19:56 UTC, alejobh commented on src/screens/SignUp/index.tsx
> +
same

2022-02-07 19:56 UTC, alejobh commented on src/screens/SignUp/index.tsx
and this

2022-02-07 20:49 UTC, alejobh approved these changes

2022-02-07 20:51 UTC, alejobh approved these changes

2022-02-07 20:55 UTC, merged