Sign up tests
wolox-training/jh-react pull request #4
Opened 2022-01-25 15:36 UTC by miguelhenaoa

## Summary

- Refactor to SignUp component and create SignUpForm component
- Create mock users
- Add unit test for some cases
## Screenshots
![image](https://user-images.githubusercontent.com/84401563/151007886-7a36f72b-2cfa-4be9-9e49-9ac5cc4d824c.png)

## Trello Card

https://trello.com/c/DCMTYFjk

2022-01-26 15:58 UTC, TaloMontes commented on src/components/SignUpForm/index.test.tsx
> +    // i18n.init();
delete comment

2022-01-26 16:12 UTC, miguelhenaoa commented on src/components/SignUpForm/index.test.tsx
> +    // i18n.init();
Done!

2022-02-07 21:27 UTC, alejobh requested changes

2022-02-07 21:27 UTC, alejobh commented on src/components/SignUpForm/index.tsx
> +
delete this line

2022-02-07 21:27 UTC, alejobh commented on src/components/Wrapper/index.tsx
> +  return <div className={styles.wrapper}>{children}</div>;
this should render `<FormCard>` too

2022-02-07 21:27 UTC, alejobh commented on src/components/Wrapper/styles.module.scss
> +@import "../../scss/variables/colors";
does this work? `@import "variables/colors";`

2022-02-07 21:27 UTC, alejobh commented on src/components/SignUpForm/index.tsx
> +type Props = {
this should be an interface

2022-02-07 21:27 UTC, alejobh commented on src/components/SignUpForm/index.tsx
> +
delete line

2022-02-07 22:02 UTC, alejobh approved these changes

2022-02-07 22:04 UTC, alejobh approved these changes

2022-02-07 22:04 UTC, merged